---

# Create VirtualEnv

#TODO

# Install requirements

- name: app_bookkeeping-apt
  apt: pkg=$item state=installed
  with_items:
    - libpq-dev
    - python-dev

# Install wheel requirements

#TODO

# Get Git sources

- name: /srv/www/apps
  file: path=/srv/www/apps state=directory owner=www-data group=www-data

- name: app_bookkeeping_git
  git: repo=https://github.com/aert/aert-bookkeeping.git dest=/srv/www/apps/aert-bookkeeping.git update=yes force=yes

# Migrate db

#TODO

# Configure uWSGI

- name: app_bookkeeping_uwsgi-config
  template: src=uwsgi.ini.j2 dest=/etc/uwsgi/apps-available/bookkeeping.ini
  notify:
    - restart uwsgi

- name: app_bookkeeping_uwsgi-enable
  file: src=/etc/uwsgi/apps-available/bookkeeping.ini dest=/etc/uwsgi/apps-enabled/bookkeeping.ini state=link
